### ISSUE TITLE
Build command

### ISSUE THREAD

**Issue by ivansantiagojr** [brasilisclub/resma-cli#3]
The `resma build` command creates a public folder with all the contents of the website. Inside the `public` folder, every page of your site will be a folder (or sub-folder) containing a index.html file. 

Steps to achieve this task:
- [x] define a markdown "header" configuration to set which template should be used to create that page
- [x] define structure to public folder

Tools and libraries:
- [markdown](https://python-markdown.github.io/) Python library for markdown to html conversions;

Check our file structure and other details on [README.md](https://github.com/getresma/resma-cli/blob/main/README.md).

**Comment by ivansantiagojr** [comment]
In order to identify a resma project, when running the build command, there should be a `config.toml` file in the current directory. Also, this file should contain a `resma` table.

**Comment by thigcampos** [comment]
### /contents
For every `.md` file in `/contents` will generate a new page in your website. Check for each folder inside `/contents`, the ones with a `_index.md` file are a new section. Inside the folder with `_index.md`, every other `.md` file will be a page. 

##### Example
- `/contents/about.md` will generate a page available in the URL `yourdomain.com/about`;
- `/contents/blog/_index.md` will generate a section available in the URL `yourdomain.com/blog`;
- `/contents/blog/new-post.md` will generate a page available in the URL `yourdomain.com/blog/new-post`;
The **blog** section will group all `.md` files inside the `/contents/blog` folder. Ideally, the `yourdomain.com/blog` should list all posts within the `blog` section.

### /contents/post.md
All the content, title and everything will be delivered to the Jinja templates through the 'page' variable, which is a dict. This dict have the following structure:
```py
page = {
		'title': '...', # page.title (a string)
		'content' '...', # page.content (html converted content)
		'extras': {...} # this is a table from the frontmatter of the file
}
```
Front-matter options:
```toml
+++
title = 'title' # required
template 'path/to/template.html' # required
[extras] # extras table, optional
key = 'key' # optional value
+++
```
### /public
For every section or page, a folder will be created in the `public` folder with its own `index.html` file.

**Comment by ivansantiagojr** [comment]
Implement on #5
